# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Janus\Desktop\nasa\primera_paginas.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_priPag(object):
    def setupUi(self, priPag):
        priPag.setObjectName("priPag")
        priPag.resize(602, 890)
        self.centralwidget = QtWidgets.QWidget(priPag)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(30, 40, 231, 201))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(340, 40, 231, 201))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(30, 280, 231, 201))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(340, 280, 231, 201))
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(30, 520, 231, 201))
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_6.setGeometry(QtCore.QRect(340, 520, 231, 201))
        self.textEdit_6.setObjectName("textEdit_6")
        priPag.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(priPag)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 602, 21))
        self.menubar.setObjectName("menubar")
        priPag.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(priPag)
        self.statusbar.setObjectName("statusbar")
        priPag.setStatusBar(self.statusbar)

        self.retranslateUi(priPag)
        QtCore.QMetaObject.connectSlotsByName(priPag)

    def retranslateUi(self, priPag):
        _translate = QtCore.QCoreApplication.translate
        priPag.setWindowTitle(_translate("priPag", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    priPag = QtWidgets.QMainWindow()
    ui = Ui_priPag()
    ui.setupUi(priPag)
    priPag.show()
    sys.exit(app.exec_())
